from stack import Stack

stack = Stack(2)
stack.display()
stack.insert(20)
stack.display()
stack.insert(5)
stack.display()
print(stack.pop())
stack.display()
print(stack.get_min())
stack.insert(-1)
stack.display()
stack.insert(3)
stack.display()
stack.insert(10)
stack.display()
print(stack.get_min())
print(stack.pop())
stack.display()
stack.pop(2)
stack.display()
stack.insert(4)
stack.display()
stack.insert(0)
stack.display()
stack.insert(1)
stack.display()
print(stack.get_min())